name: Pylint Badge

on:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint requests python-dotenv tqdm

      - name: Run pylint and extract score
        run: |
          pylint main.py > pylint.log || true
          SCORE=$(tail -n 2 pylint.log | grep -Po '[0-9]+\.[0-9]+(?=/10)')
          echo "Pylint score: $SCORE"

          # Badge color by score
          if (( $(echo "$SCORE >= 9" | bc -l) )); then
            COLOR="brightgreen"
          elif (( $(echo "$SCORE >= 7" | bc -l) )); then
            COLOR="yellow"
          else
            COLOR="red"
          fi

          curl "https://img.shields.io/badge/pylint-$SCORE/10-$COLOR" -o pylint_score.svg

      - name: Commit badge
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          git add pylint_score.svg
          COMMIT_HASH=$(git rev-parse --short HEAD)
          git commit -m "Atualiza badge pylint (commit $COMMIT_HASH)" || echo "Sem mudanças"
          git push https
