name: Pylint Badge

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint requests python-dotenv tqdm

      - name: Run pylint and extract score
        run: |
          pylint main.py > pylint.log || true
          SCORE=$(tail -n 2 pylint.log | grep -Po '[0-9]+\.[0-9]+(?=/10)')
          echo "Pylint score: $SCORE"
          curl "https://img.shields.io/badge/pylint-$SCORE/10-brightgreen" -o pylint_score.svg

      - name: Commit badge
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add pylint_score.svg
          git commit -m "Atualiza badge pylint" || echo "Sem mudanças"
          git push origin main
